services:
  mariadb-db:
    image: mariadb:latest             # MariaDB 이미지
    container_name: my-mariadb        # 컨테이너 이름
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234   # root 비밀번호
      MYSQL_DATABASE: mydb            # 기본 DB명
      MYSQL_USER: myuser              # 사용자 계정
      MYSQL_PASSWORD: mypass1234      # 사용자 비밀번호
    ports:
      - "3307:3306"                   # MySQL 3308, MariaDB 3307
    volumes:
      - ./data:/var/lib/mysql         # 볼륨